# TF-IDF

<font face='georgia'>
    
   <h4><strong>What does tf-idf mean?</strong></h4>

   <p>    
Tf-idf stands for <em>term frequency-inverse document frequency</em>, and the tf-idf weight is a weight often used in information retrieval and text mining. This weight is a statistical measure used to evaluate how important a word is to a document in a collection or corpus. The importance increases proportionally to the number of times a word appears in the document but is offset by the frequency of the word in the corpus. Variations of the tf-idf weighting scheme are often used by search engines as a central tool in scoring and ranking a document's relevance given a user query.
</p>
    
   <p>
One of the simplest ranking functions is computed by summing the tf-idf for each query term; many more sophisticated ranking functions are variants of this simple model.
</p>
    
   <p>
Tf-idf can be successfully used for stop-words filtering in various subject fields including text summarization and classification.
</p>
    
</font>

<font face='georgia'>
    <h4><strong>How to Compute:</strong></h4>

Typically, the tf-idf weight is composed by two terms: the first computes the normalized Term Frequency (TF), aka. the number of times a word appears in a document, divided by the total number of words in that document; the second term is the Inverse Document Frequency (IDF), computed as the logarithm of the number of the documents in the corpus divided by the number of documents where the specific term appears.

 <ul>
    <li>
<strong>TF:</strong> Term Frequency, which measures how frequently a term occurs in a document. Since every document is different in length, it is possible that a term would appear much more times in long documents than shorter ones. Thus, the term frequency is often divided by the document length (aka. the total number of terms in the document) as a way of normalization: <br>

$TF(t) = \frac{\text{Number of times term t appears in a document}}{\text{Total number of terms in the document}}.$
</li>
<li>
<strong>IDF:</strong> Inverse Document Frequency, which measures how important a term is. While computing TF, all terms are considered equally important. However it is known that certain terms, such as "is", "of", and "that", may appear a lot of times but have little importance. Thus we need to weigh down the frequent terms while scale up the rare ones, by computing the following: <br>

$IDF(t) = \log_{e}\frac{\text{Total  number of documents}} {\text{Number of documents with term t in it}}.$
for numerical stabiltiy we will be changing this formula little bit
$IDF(t) = \log_{e}\frac{\text{Total  number of documents}} {\text{Number of documents with term t in it}+1}.$
</li>
</ul>

<br>
<h4><strong>Example</strong></h4>
<p>

Consider a document containing 100 words wherein the word cat appears 3 times. The term frequency (i.e., tf) for cat is then (3 / 100) = 0.03. Now, assume we have 10 million documents and the word cat appears in one thousand of these. Then, the inverse document frequency (i.e., idf) is calculated as log(10,000,000 / 1,000) = 4. Thus, the Tf-idf weight is the product of these quantities: 0.03 * 4 = 0.12.
</p>
</font>

## Task-1

<font face='georgia'>
    <h4><strong>1. Build a TFIDF Vectorizer & compare its results with Sklearn:</strong></h4>

<ul>
    <li> As a part of this task you will be implementing TFIDF vectorizer on a collection of text documents.</li>
    <br>
    <li> You should compare the results of your own implementation of TFIDF vectorizer with that of sklearns implemenation TFIDF vectorizer.</li>
    <br>
    <li> Sklearn does few more tweaks in the implementation of its version of TFIDF vectorizer, so to replicate the exact results you would need to add following things to your custom implementation of tfidf vectorizer:
       <ol>
        <li> Sklearn has its vocabulary generated from idf sroted in alphabetical order</li>
        <li> Sklearn formula of idf is different from the standard textbook formula. Here the constant <strong>"1"</strong> is added to the numerator and denominator of the idf as if an extra document was seen containing every term in the collection exactly once, which prevents zero divisions.
            
 $IDF(t) = 1+\log_{e}\frac{1\text{ }+\text{ Total  number of documents in collection}} {1+\text{Number of documents with term t in it}}.$
        </li>
        <li> Sklearn applies L2-normalization on its output matrix.</li>
        <li> The final output of sklearn tfidf vectorizer is a sparse matrix.</li>
    </ol>
    <br>
    <li>Steps to approach this task:
    <ol>
        <li> You would have to write both fit and transform methods for your custom implementation of tfidf vectorizer.</li>
        <li> Print out the alphabetically sorted voacb after you fit your data and check if its the same as that of the feature names from sklearn tfidf vectorizer. </li>
        <li> Print out the idf values from your implementation and check if its the same as that of sklearns tfidf vectorizer idf values. </li>
        <li> Once you get your voacb and idf values to be same as that of sklearns implementation of tfidf vectorizer, proceed to the below steps. </li>
        <li> Make sure the output of your implementation is a sparse matrix. Before generating the final output, you need to normalize your sparse matrix using L2 normalization. You can refer to this link https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.normalize.html </li>
        <li> After completing the above steps, print the output of your custom implementation and compare it with sklearns implementation of tfidf vectorizer.</li>
        <li> To check the output of a single document in your collection of documents,  you can convert the sparse matrix related only to that document into dense matrix and print it.</li>
        </ol>
    </li>
    <br>
   </ul>

  <p> <font color="#e60000"><strong>Note-1: </strong></font> All the necessary outputs of sklearns tfidf vectorizer have been provided as reference in this notebook, you can compare your outputs as mentioned in the above steps, with these outputs.<br>
   <font color="#e60000"><strong>Note-2: </strong></font> The output of your custom implementation and that of sklearns implementation would match only with the collection of document strings provided to you as reference in this notebook. It would not match for strings that contain capital letters or punctuations, etc, because sklearn version of tfidf vectorizer deals with such strings in a different way. To know further details about how sklearn tfidf vectorizer works with such string, you can always refer to its official documentation.<br>
   <font color="#e60000"><strong>Note-3: </strong></font> During this task, it would be helpful for you to debug the code you write with print statements wherever necessary. But when you are finally submitting the assignment, make sure your code is readable and try not to print things which are not part of this task.
    </p>

### Corpus

In [1]:
## SkLearn Collection of string documents

corpus = [
     'this is the first document',
     'this document is the second document',
     'and this is the third one',
     'is this the first document',
]

### SkLearn Implementation

In [2]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()
vectorizer.fit(corpus)
skl_output = vectorizer.transform(corpus)

In [3]:
# sklearn feature names, they are sorted in alphabetic order by default.

print(vectorizer.get_feature_names())

AttributeError: 'TfidfVectorizer' object has no attribute 'get_feature_names'

In [ ]:
# Here we will print the sklearn tfidf vectorizer idf values after applying the fit method
# After using the fit function on the corpus the vocab has 9 words in it, and each has its idf value.

print(vectorizer.idf_)

[1.91629073 1.22314355 1.51082562 1.         1.91629073 1.91629073
 1.         1.91629073 1.        ]


In [ ]:
# shape of sklearn tfidf vectorizer output after applying transform method.

skl_output.shape

(4, 9)

In [ ]:
# sklearn tfidf values for first line of the above corpus.
# Here the output is a sparse matrix

print(skl_output[0])

  (0, 8)	0.38408524091481483
  (0, 6)	0.38408524091481483
  (0, 3)	0.38408524091481483
  (0, 2)	0.5802858236844359
  (0, 1)	0.46979138557992045


In [ ]:
# sklearn tfidf values for first line of the above corpus.
# To understand the output better, here we are converting the sparse output matrix to dense matrix and printing it.
# Notice that this output is normalized using L2 normalization. sklearn does this by default.

print(skl_output[0].toarray())

[[0.         0.46979139 0.58028582 0.38408524 0.         0.
  0.38408524 0.         0.38408524]]


### Your custom implementation

In [16]:
# dependencies
from collections import Counter
from tqdm import tqdm
from scipy.sparse import csr_matrix
import math
import operator
from sklearn.preprocessing import normalize
import numpy

In [17]:
# Write your code here.
# Make sure its well documented and readble with appropriate comments.
# Compare your results with the above sklearn tfidf vectorizer
# You are not supposed to use any other library apart from the ones given below



class CustomVectorizer(object):
    def __init__(self):
        self.result = set()

    def fit(self, corpus: list[str]):
        "Return collection of unique words in corpus" 
        # result = set() # different words to be stored 
        # Check for corpus to be actual corpus
        if not isinstance(corpus, (list)):
            raise TypeError
        for sentence in corpus:
            # tokenizing sentence into words container
            sentence = sentence.lower()
            for word in sentence.split(" "):
                # Removing letter like a, i and other raw letter
                if len(word) >= 2:
                    self.result.add(word)
        self.result = sorted(list(self.result))
        
        vocab = {j:i for i, j in enumerate(self.result)}
        return vocab 
    
    def get_feature_names(self):
        return list(self.result)
    
    def TF(self, corpus, vocab):
        """This function computes the term-frequency of corpus
        formula = tf(W_i, R_j) = (No of times W_i occurs in R_j) / (Total words in R_j)

        return: dict with term frequencies
        """
        tf_ = {}
        
        for sentence in corpus:
            words = sentence.split(" ")
            LEN = len(words)
            freqMap = dict(Counter(words))
            for key in vocab.keys():
               tf_[key] = (freqMap[key]/LEN)
        return tf_ 
      
    def IDF(self, corpus, vocab):
        """This function return IDF values 
        return : dictionary contains idf vaglues
        """
        idf_ = {}
        N = len(corpus) # No of docs
        for key in vocab.keys():
            n = 0 # Initially key occurence is ZERO
            for sentence in corpus:
                if key in sentence:
                    n = n + 1 # n is n_i 
            # Computing idf
            idf_[key] = 1 + (math.log((1 + N)/(1 + n)) ) # as per the formula above
        
        return idf_
    
    def transform(self, corpus, vocab):
        rows=[]
        colums=[]
        values=[]
        if isinstance(corpus, (list,)):
            for idx, sentence in enumerate(tqdm(corpus)):
                freqMap = dict(Counter(sentence.split(" ")))

                for word, freq in freqMap.items():
                    if len(word) >= 2:
                        colIndex = vocab.get(word, -1)
                        if colIndex != -1:
                            rows.append(idx)
                            colums.append(colIndex)
                            values.append(freq)
        return csr_matrix((values, (rows,colums)), shape=(len(corpus),len(vocab)))
                
  


``` Features matched succesfully ```

In [18]:

Vector = CustomVectorizer()
vocab = Vector.fit(corpus)
print(Vector.get_feature_names())

['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third', 'this']


In [19]:
from pprint import pprint
pprint(Vector.IDF(corpus, vocab))

{'and': 1.916290731874155,
 'document': 1.2231435513142097,
 'first': 1.5108256237659907,
 'is': 1.0,
 'one': 1.916290731874155,
 'second': 1.916290731874155,
 'the': 1.0,
 'third': 1.916290731874155,
 'this': 1.0}


In [20]:
strings = ["the method of lagrange multipliers is the economists workhorse for solving optimization problems",
           "the technique is a centerpiece of economic theory but unfortunately its usually taught poorly"]
vector = CustomVectorizer()
vocab = vector.fit(strings)
print(list(vocab.keys()))
print(vector.transform(strings, vocab).toarray())

['but', 'centerpiece', 'economic', 'economists', 'for', 'is', 'its', 'lagrange', 'method', 'multipliers', 'of', 'optimization', 'poorly', 'problems', 'solving', 'taught', 'technique', 'the', 'theory', 'unfortunately', 'usually', 'workhorse']


100%|██████████| 2/2 [00:00<00:00, 11586.48it/s]

[[0 0 0 1 1 1 0 1 1 1 1 1 0 1 1 0 0 2 0 0 0 1]
 [1 1 1 0 0 1 1 0 0 0 1 0 1 0 0 1 1 1 1 1 1 0]]


``` IDF values matched succesfully ```

## Task-2

<font face='georgia'>
    <h4><strong>2. Implement max features functionality:</strong></h4>

<ul>
    <li> As a part of this task you have to modify your fit and transform functions so that your vocab will contain only 50 terms with top idf scores.</li>
    <br>
    <li>This task is similar to your previous task, just that here your vocabulary is limited to only top 50 features names based on their idf values. Basically your output will have exactly 50 columns and the number of rows will depend on the number of documents you have in your corpus.</li>
    <br>
    <li>Here you will be give a pickle file, with file name <strong>cleaned_strings</strong>. You would have to load the corpus from this file and use it as input to your tfidf vectorizer.</li>
    <br>
    <li>Steps to approach this task:
    <ol>
        <li> You would have to write both fit and transform methods for your custom implementation of tfidf vectorizer, just like in the previous task. Additionally, here you have to limit the number of features generated to 50 as described above.</li>
        <li> Now sort your vocab based in descending order of idf values and print out the words in the sorted voacb after you fit your data. Here you should be getting only 50 terms in your vocab. And make sure to print idf values for each term in your vocab. </li>
        <li> Make sure the output of your implementation is a sparse matrix. Before generating the final output, you need to normalize your sparse matrix using L2 normalization. You can refer to this link https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.normalize.html </li>
        <li> Now check the output of a single document in your collection of documents,  you can convert the sparse matrix related only to that document into dense matrix and print it. And this dense matrix should contain 1 row and 50 columns. </li>
        </ol>
    </li>
    <br>
   </ul>

In [21]:
# Below is the code to load the cleaned_strings pickle file provided
# Here corpus is of list type

import pickle
with open('cleaned_strings', 'rb') as f:
    corpus = pickle.load(f)
    
# printing the length of the corpus loaded
print("Number of documents in corpus = ",len(corpus))

Number of documents in corpus =  746


In [57]:
# Write your code here.
# Try not to hardcode any values.
# Make sure its well documented and readble with appropriate comments.
import math
from collections import Counter
class CustomVectorizerTop50(object):
    def fit(self, corpus: list[str]):
        "Return collection of unique words in corpus" 
        result = set() # different words to be stored 
        # Check for corpus to be actual corpus
        
        if not isinstance(corpus, (list)):
            raise TypeError
        for sentence in corpus:
            # tokenizing sentence into words container
            sentence = sentence.lower()
            for word in sentence.split(" "):
                # Removing letter like a, i and other raw letter
                if len(word) >= 2:
                    result.add(word)
        result = sorted(list(result))
        
        vocab = {j:i for i, j in enumerate(result)}
        
        return vocab 
    
    def IDF(self, corpus, vocab):
        idf = {}
        N = len(corpus)
        # Computing normal idf values
        for key in vocab.keys():
            n = 0
            for sentence in corpus:
                if key in sentence:
                    n = n + 1
                idf[key] = 1 + (math.log((1+N)/(1+n)))
        # Retreiving top 50 vals 
        idf_sort = {}
        for key in sorted(idf, key= lambda x: idf[x], reverse=True):
            idf_sort[key] = idf[key]
        
        #Refer - https://www.geeksforgeeks.org/python-program-to-find-the-highest-3-values-in-a-dictionary/
        # {word: idf-values}
        k=Counter(idf_sort)
        idf_50 = {}
        top50=dict(k.most_common(50))  # List[('key', value)]
        top_50_vocab= {}  
        idx = 0  
        for key in top50: # key = idx[0] , val = idx[1] 
            top_50_vocab[key] = idx
            idf_50[key] = top50[key]
            idx += 1 
        return top_50_vocab, idf_50
    
    def transform(self, corpus, top_50_vocab):
        rows=[]
        colums=[]
        values=[]
        if isinstance(corpus, (list,)):
            for idx, sentence in enumerate(tqdm(corpus)):
                freqMap = dict(Counter(sentence.split(" ")))

                for word, freq in freqMap.items():
                    if len(word) >= 2:
                        colIndex = top_50_vocab.get(word, -1)
                        if colIndex != -1:
                            rows.append(idx)
                            colums.append(colIndex)
                            values.append(freq)
        return normalize(csr_matrix((values, (rows,colums)), shape=(len(corpus),len(top_50_vocab))), norm='l2')
        

In [58]:
instance = CustomVectorizerTop50() 
vocab=  instance.fit(corpus)
vocab50,idf50=instance.IDF(corpus,vocab)            

In [59]:
from pprint import pprint
pprint(vocab50) 

{'aailiyah': 0,
 'abandoned': 1,
 'abroad': 2,
 'abstruse': 3,
 'academy': 4,
 'accents': 5,
 'accessible': 6,
 'acclaimed': 7,
 'accolades': 8,
 'accurately': 9,
 'achille': 10,
 'ackerman': 11,
 'adams': 12,
 'added': 13,
 'admins': 14,
 'admiration': 15,
 'admitted': 16,
 'adrift': 17,
 'adventure': 18,
 'aesthetically': 19,
 'affected': 20,
 'affleck': 21,
 'afternoon': 22,
 'agreed': 23,
 'aimless': 24,
 'aired': 25,
 'akasha': 26,
 'alert': 27,
 'alike': 28,
 'allison': 29,
 'allowing': 30,
 'alongside': 31,
 'amateurish': 32,
 'amazed': 33,
 'amazingly': 34,
 'amusing': 35,
 'amust': 36,
 'anatomist': 37,
 'angela': 38,
 'angelina': 39,
 'angry': 40,
 'anguish': 41,
 'angus': 42,
 'animals': 43,
 'animated': 44,
 'anita': 45,
 'anniversary': 46,
 'anthony': 47,
 'antithesis': 48,
 'anyway': 49}


In [60]:
pprint(idf50)

{'aailiyah': 6.922918004572872,
 'abandoned': 6.922918004572872,
 'abroad': 6.922918004572872,
 'abstruse': 6.922918004572872,
 'academy': 6.922918004572872,
 'accents': 6.922918004572872,
 'accessible': 6.922918004572872,
 'acclaimed': 6.922918004572872,
 'accolades': 6.922918004572872,
 'accurately': 6.922918004572872,
 'achille': 6.922918004572872,
 'ackerman': 6.922918004572872,
 'adams': 6.922918004572872,
 'added': 6.922918004572872,
 'admins': 6.922918004572872,
 'admiration': 6.922918004572872,
 'admitted': 6.922918004572872,
 'adrift': 6.922918004572872,
 'adventure': 6.922918004572872,
 'aesthetically': 6.922918004572872,
 'affected': 6.922918004572872,
 'affleck': 6.922918004572872,
 'afternoon': 6.922918004572872,
 'agreed': 6.922918004572872,
 'aimless': 6.922918004572872,
 'aired': 6.922918004572872,
 'akasha': 6.922918004572872,
 'alert': 6.922918004572872,
 'alike': 6.922918004572872,
 'allison': 6.922918004572872,
 'allowing': 6.922918004572872,
 'alongside': 6.9229180

In [61]:
print(list(vocab50.keys()))
print(instance.transform(corpus, vocab50).toarray())


['aailiyah', 'abandoned', 'abroad', 'abstruse', 'academy', 'accents', 'accessible', 'acclaimed', 'accolades', 'accurately', 'achille', 'ackerman', 'adams', 'added', 'admins', 'admiration', 'admitted', 'adrift', 'adventure', 'aesthetically', 'affected', 'affleck', 'afternoon', 'agreed', 'aimless', 'aired', 'akasha', 'alert', 'alike', 'allison', 'allowing', 'alongside', 'amateurish', 'amazed', 'amazingly', 'amusing', 'amust', 'anatomist', 'angela', 'angelina', 'angry', 'anguish', 'angus', 'animals', 'animated', 'anita', 'anniversary', 'anthony', 'antithesis', 'anyway']


100%|██████████| 746/746 [00:00<00:00, 84655.47it/s]

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


All Test passed

Reference - 
```
i.) attached notebook
ii.) Geeks for Geeks 
iii.) Stack overflow 
iv.) Sklearn.tfiidfvectorizer 
```